### ISSUE TITLE
skills filename or directory name or volume label syntax is incorrect 

### ISSUE THREAD

**Issue by udin39** [Arham4/RuneBot#23]
self host btw . got some error popping out whenever i typed out r.skills . everything is fine . its just the skills it wont show the image and produce this error 

java.io.FileNotFoundException: .\data\images\skills_>o<.png (The filename, directory name, or volume label syntax is incorrect)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at javax.imageio.stream.FileImageOutputStream.<init>(FileImageOutputStream.java:69)
        at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(FileImageOutputStreamSpi.java:55)
        at javax.imageio.ImageIO.createImageOutputStream(ImageIO.java:419)
        at javax.imageio.ImageIO.write(ImageIO.java:1530)
        at com.gmail.arhamjsiddiqui.runebot.commands.SkillsCommand.onSkillsCommand(SkillsCommand.kt:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at de.btobastian.sdcf4j.handler.JDA3Handler.invokeMethod(JDA3Handler.java:147)
        at de.btobastian.sdcf4j.handler.JDA3Handler.lambda$handleMessageCreate$0(JDA3Handler.java:127)
        at java.lang.Thread.run(Thread.java:748)
Jul 30, 2018 2:26:59 PM de.btobastian.sdcf4j.handler.JDA3Handler invokeMethod
WARNING: An error occurred while invoking method onSkillsCommand!
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at de.btobastian.sdcf4j.handler.JDA3Handler.invokeMethod(JDA3Handler.java:147)
        at de.btobastian.sdcf4j.handler.JDA3Handler.lambda$handleMessageCreate$0(JDA3Handler.java:127)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at javax.imageio.ImageIO.write(ImageIO.java:1538)
        at com.gmail.arhamjsiddiqui.runebot.commands.SkillsCommand.onSkillsCommand(SkillsCommand.kt:51)
        ... 7 more

**Comment by udin39** [comment]
nvm. fixed it because the bot wont read symbols only username for example my username on discord is >o< . basically it cant read it .

**Comment by Arham4** [comment]
Make an issue on file names, please @udin39. I may just end up saving the files based on Discord ID instead. Thank you!
